### ISSUE TITLE
加载不到dll

### ISSUE THREAD

**Issue by KOLLSOFT** [chaoyu1999/FPSAutomaticAiming#2]
### err msg:
Fusing layers...
Traceback (most recent call last):
  File "Main.py", line 12, in <module>
    dll = cdll.LoadLibrary(r'lib/Dll.dll')  # 加载用C语言封装过的“易键鼠”dll
  File "C:\Users\Test\anaconda3\envs\yolo\lib\ctypes\__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\Test\anaconda3\envs\yolo\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\Work\opensource\FPSAutomaticAiming\lib\Dll.dll' (or one of its dependencies). Try using the full path with constructor syntax.

------
是需要安装其他的库吗？

**Comment by chaoyu1999** [comment]
建议自己将dll重新封装编译一遍，因为每台电脑的环境都不太一样，不保证每个电脑都能用我封装的dll

**Comment by chaoyu1999** [comment]
https://github.com/chaoyu1999/FPSAutomaticAiming/blob/main/lib/VS%E5%B0%81%E8%A3%85%E6%98%93%E9%94%AE%E9%BC%A0dll.zip封装dll的vs项目在这

**Comment by chaoyu1999** [comment]
https://github.com/chaoyu1999/FPSAutomaticAiming/blob/main/lib/VS%E5%B0%81%E8%A3%85%E6%98%93%E9%94%AE%E9%BC%A0dll.zip
封装dll的项目在这

**Comment by tuziqq** [comment]
怎么重写编译呀
