### ISSUE TITLE
conda引入之后运行main.py

### ISSUE THREAD

**Issue by kbcjk** [chaoyu1999/FPSAutomaticAiming#28]
D:\FPSAutomaticAiming>py main.py
Traceback (most recent call last):
  File "D:\FPSAutomaticAiming\main.py", line 4, in <module>
    from FPSDetect import *
  File "D:\FPSAutomaticAiming\FPSDetect.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by chaoyu1999** [comment]
环境没配置好

**Comment by cadenwong552** [comment]
You need to activate your conda environment first and run `python main.py` instead of using the global
